import { bilingual, type Language } from "@/lib/i18n";
import type { NodeKind } from "./scene";

// Level and source-type names are shared by every homepage module.
export { LEVEL_NAMES as LEVELS, TIER_NAMES as TIERS } from "@/components/home/sections/levels";

export const KIND_NAMES: Record<Language, Record<NodeKind, string>> = {
  en: { domain: "Domains", market: "Markets", work: "Work", update: "Updates", org: "Companies" },
  "zh-CN": { domain: "领域", market: "赛道", work: "工作", update: "更新", org: "公司" },
};

export const copy = bilingual({
  en: {
    eyebrow: "Updated {date} · Tracking {n} AI companies since {start}",
    headline: "How far AI has taken over the world",
    subtitle: "Will AI kill your idea? Replace what you do?",
    supporting: "Every AI update could change your answer.",
    ticker: "{n} updates this day",
    dayOf: "{weekday} · Day {day} of {days} · UTC",
    dayPanel: "Updates that day",
    dayEmpty: "No updates",
    cUpdate: "Updates",
    cWork: "Work reached by an update",
    cWorkSub: "{n} in the catalogue",
    cL3: "L3 Conditional automation",
    cCapped: "Claimed above accepted",
    cDomain: "Domains",
    cMarket: "Markets",
    cOrg: "Companies",
    cToday: "Updates this day",
    related: "Related {n}",
    reset: "Reset",
    legendLit: "Links of the selected node",
    legendCapped: "Claimed level above accepted level",
    legendSeveral: "Confirmed by several sources",
    legendLine: "L3 line: At L0–L2, a person is still doing the work. From L3, a person is no longer doing it.",
    search: "Search work, markets, companies, updates",
    noMatch: "Nothing matches under the current filters",
    acceptedLevel: "Accepted level",
    fCapped: "Claimed above accepted",
    fSeveral: "Confirmed by several sources",
    fOrg: "Company",
    fDomain: "Domain",
    fClear: "Clear filters",
    keys: "Scroll down for detail · Space play/pause · ← → day · Esc close · Backspace back · / search",
    play: "Play",
    pause: "Pause",
    dayUpdates: "{date}: {n} updates",
    accepted: "Accepted",
    claimed: "Claimed",
    updatesN: "{n} updates",
    undated: "undated",
    backOverview: "← Back to overview",
    backTo: "← Back: {name}",
    close: "✕ Close",
    publisherOnly: "This claim comes only from the publisher. L3 and above require confirmation from other sources.",
    source: "Source ↗",
    openWork: "Open this work →",
    openUpdate: "Open this update →",
    original: "Title in the original language",
    more: "… {n} more",
    panelLabel: "Selection",
    domainLabel: "{name} · L{level} · {n}",
    stageLabel: "Interactive overview of AI updates, the work they bear on and the level reached",
  },
  "zh-CN": {
    eyebrow: "更新于 {date} · 自 {start} 起观测 {n} 家 AI 公司",
    headline: "AI 接管世界的进度",
    subtitle: "AI 会杀死你的想法？取代你的工作能力？",
    supporting: "每一次 AI 更新，都可能会挑战你的答案。",
    ticker: "当天 {n} 条更新",
    dayOf: "{weekday} · 第 {day} / {days} 天 · UTC",
    dayPanel: "当天更新",
    dayEmpty: "没有更新",
    cUpdate: "更新",
    cWork: "已有更新涉及的工作",
    cWorkSub: "目录中 {n} 项",
    cL3: "L3 有条件自动化",
    cCapped: "宣称高于采信",
    cDomain: "领域",
    cMarket: "赛道",
    cOrg: "公司",
    cToday: "当天更新",
    related: "所选相关 {n}",
    reset: "复位",
    legendLit: "所选节点的连接",
    legendCapped: "宣称级别高于采信级别",
    legendSeveral: "多方印证",
    legendLine: "L3 线：L0–L2，人仍在干这件活；L3 起，人不再干这件活。",
    search: "搜索工作、赛道、公司、更新",
    noMatch: "当前筛选下没有匹配",
    acceptedLevel: "采信级别",
    fCapped: "宣称高于采信",
    fSeveral: "多方印证",
    fOrg: "公司",
    fDomain: "领域",
    fClear: "清除筛选",
    keys: "向下滚动看明细 · 空格 播放/暂停 · ← → 换日期 · Esc 关闭 · 退格 返回 · / 搜索",
    play: "播放",
    pause: "暂停",
    dayUpdates: "{date}：{n} 条更新",
    accepted: "采信",
    claimed: "宣称",
    updatesN: "{n} 条更新",
    undated: "未标日期",
    backOverview: "← 返回全览",
    backTo: "← 返回：{name}",
    close: "✕ 关闭",
    publisherOnly: "该说法仅来自发布方。L3 及以上需要其他来源印证。",
    source: "来源 ↗",
    openWork: "打开这项工作 →",
    openUpdate: "打开这条更新 →",
    original: "标题为原文",
    more: "… 另有 {n}",
    panelLabel: "所选内容",
    domainLabel: "{name} · L{level} · {n}",
    stageLabel: "可操作的全览：AI 更新、它们涉及的工作与达到的级别",
  },
});

/** Fills `{name}` slots in a copy string. */
export function fill(text: string, values: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (slot, key: string) => (key in values ? String(values[key]) : slot));
}
