import { bilingual } from "@/lib/i18n";

/**
 * Copy for the two market pages, in one file because the server page and the
 * interactive part of the same page have to say the same words, and a client
 * component cannot reach into the snapshot module to fetch them.
 *
 * One line of lead per block. Terms are never restated here: every rung word
 * comes from `progress.levels` in the published snapshot and is passed in.
 */

export const indexCopy = bilingual({
  en: {
    eyebrow: "Markets",
    title: "Markets",
    lead: "A kind of work a business sells. An AI update lands here, not on a job title.",
    statMarkets: "Markets",
    statMarketsNote: "{n} kinds of work in them",
    statCovered: "With evidence",
    statCoveredNote: "{n} more that no update mentioned",
    statTop: "Furthest level reached",
    statTopTag: "{n} markets",
    statTopBlank: "No market has evidence yet",
    distTitle: "Where the evidence landed",
    distLead: "Pick a rung to see only the markets that reached it.",
    blankRung: "No evidence",
    blankWord: "No collected update mentioned these markets",
    tableTitle: "All markets",
    tableLead: "A blank market means nothing was collected about it, not that AI does none of it.",
    tableLabel: "Markets table",
    searchLabel: "Search",
    searchPlaceholder: "English or Chinese name",
    coverageLabel: "Evidence",
    coverageAll: "All",
    coverageWith: "With evidence",
    coverageWithout: "No evidence",
    sortLabel: "Sort by",
    sortTop: "Furthest level",
    sortActivities: "Work",
    sortScored: "With evidence",
    sortOccupations: "Occupations",
    showing: "Showing {n} of {total} markets",
    colMarket: "Market",
    colActivities: "Work",
    colAssessed: "With evidence",
    colTop: "Furthest level reached",
    colOccupations: "Occupations served",
    noReading: "no update mentioned it",
    emptyTitle: "No market matches.",
    emptyWhy: "No market name contains what you typed, at the rung and coverage you picked.",
    reset: "Clear the filters",
    empty: "No market is published in this snapshot.",
  },
  "zh-CN": {
    eyebrow: "赛道",
    title: "赛道",
    lead: "企业卖给客户的一类工作。AI 更新落在这里，不落在职位上。",
    statMarkets: "赛道",
    statMarketsNote: "其中共 {n} 项工作",
    statCovered: "有证据",
    statCoveredNote: "另有 {n} 个赛道没被任何更新谈到",
    statTop: "已达到的最高层级",
    statTopTag: "{n} 个赛道",
    statTopBlank: "还没有赛道拿到证据",
    distTitle: "证据落在了哪里",
    distLead: "点一级，只看达到那一级的赛道。",
    blankRung: "无证据",
    blankWord: "采集到的更新里没有一条谈到这些赛道",
    tableTitle: "全部赛道",
    tableLead: "赛道是空的，只说明没采集到它，不说明 AI 做不了。",
    tableLabel: "赛道表",
    searchLabel: "搜索",
    searchPlaceholder: "中文名或英文名",
    coverageLabel: "证据",
    coverageAll: "全部",
    coverageWith: "有证据",
    coverageWithout: "无证据",
    sortLabel: "排序",
    sortTop: "最高层级",
    sortActivities: "工作数",
    sortScored: "有证据",
    sortOccupations: "服务职业数",
    showing: "显示 {total} 个赛道中的 {n} 个",
    colMarket: "赛道",
    colActivities: "工作数",
    colAssessed: "有证据",
    colTop: "已达到的最高层级",
    colOccupations: "服务的职业",
    noReading: "没有更新谈到它",
    emptyTitle: "没有赛道符合当前条件。",
    emptyWhy: "在你选的层级和证据条件下，没有赛道名包含你输入的字。",
    reset: "清除筛选",
    empty: "这份快照里没有发布任何赛道。",
  },
});

export const detailCopy = bilingual({
  en: {
    eyebrow: "Market",
    back: "All markets",
    metaSuffix: "Market",
    lead: "How far AI got on each kind of work in this market, and the update that showed it.",
    statActivities: "Work",
    statActivitiesNote: "{n} with evidence",
    statTop: "Furthest level reached",
    statTopBlank: "No update mentioned this market",
    statReadings: "Evidence",
    statReadingsNote: "{n} pulled back by an evidence tier",
    statGatedNote: "{n} held at L0 by a non-technical condition",
    activitiesTitle: "Work in this market",
    activitiesLead: "Open a row to read the updates behind its level.",
    activitiesNone: "No work is published for this market.",
    readingsLabel: "Evidence table",
    colShows: "Published",
    colJudged: "Claimed",
    colTierOne: "Evidence tier",
    colUpdate: "Update",
    colWhen: "When",
    readings: "evidence",
    tasks: "tasks",
    openWork: "Open this work",
    noReadingsTitle: "No update in the collected window mentioned this work.",
    noReadingsWhy: "That is a statement about the collection, not about the work.",
    capNote: "{tier} allows only L{cap}",
    gated: "Held by a non-technical condition",
    occupationsTitle: "Occupations this market is served by",
    occupationsLead: "One market is served by several occupations, so these are not shares of a job.",
    occupationsLabel: "Occupations table",
    occupationsNone: "No occupation has been linked to this market yet.",
    occupationsWhy: "The market-to-occupation edges are published per market; this one has none.",
    colOccupation: "Occupation",
    colConfidence: "Confidence",
    gatesTitle: "Non-technical conditions holding kinds of work here",
    gatesLead: "A non-technical condition holds a kind of work at L0 until the institution that wrote the rule changes it.",
    colGate: "Non-technical condition",
    colType: "Kind",
    colStatus: "Status",
    colHolds: "Work held here",
    noReading: "no update mentioned it",
    source: "source",
  },
  "zh-CN": {
    eyebrow: "赛道",
    back: "全部赛道",
    metaSuffix: "赛道",
    lead: "这个赛道的每项工作到了第几级，凭哪条更新。",
    statActivities: "工作",
    statActivitiesNote: "其中 {n} 条有证据",
    statTop: "已达到的最高层级",
    statTopBlank: "没有更新谈到这个赛道",
    statReadings: "证据",
    statReadingsNote: "其中 {n} 条被证据层级压低",
    statGatedNote: "{n} 条受非技术门槛限制，记在 L0",
    activitiesTitle: "这个赛道里的工作",
    activitiesLead: "点开一条，就地读它凭的那几条更新。",
    activitiesNone: "这个赛道没有发布任何工作。",
    readingsLabel: "证据表",
    colShows: "发布值",
    colJudged: "宣称级别",
    colTierOne: "证据层级",
    colUpdate: "更新",
    colWhen: "时间",
    readings: "条证据",
    tasks: "项任务",
    openWork: "打开这项工作",
    noReadingsTitle: "采集窗口里没有一条更新谈到这项工作。",
    noReadingsWhy: "这是关于采集的陈述，不是关于这份工作的陈述。",
    capNote: "{tier} 最高只支持到 L{cap}",
    gated: "受非技术门槛限制",
    occupationsTitle: "服务这个赛道的职业",
    occupationsLead: "一个赛道由多个职业共同服务，所以这些不是对某份工作的切分。",
    occupationsLabel: "职业表",
    occupationsNone: "还没有职业与这个赛道建立关联。",
    occupationsWhy: "赛道—职业的对应关系按赛道发布，这个赛道目前一条都没有。",
    colOccupation: "职业",
    colConfidence: "置信度",
    gatesTitle: "这条赛道的非技术门槛",
    gatesLead: "非技术门槛不随模型变强而解除；受限的工作记在 L0。",
    colGate: "非技术门槛",
    colType: "类型",
    colStatus: "状态",
    colHolds: "在本赛道按住",
    noReading: "没有更新谈到它",
    source: "原文",
  },
});

/** `{n}` and friends, filled in without pulling a formatter into the bundle. */
export function fill(template: string, values: Record<string, string | number>): string {
  return Object.entries(values).reduce(
    (text, [key, value]) => text.replaceAll(`{${key}}`, String(value)),
    template,
  );
}

/** One grouping for both languages, so a number never changes shape mid-page. */
const numberFormat = new Intl.NumberFormat("en-US");

export function count(value: number): string {
  return numberFormat.format(value);
}
