import { bilingual } from "@/lib/i18n";

/**
 * Copy for the two market pages, in one file because the server page and the
 * interactive part of the same page have to say the same words, and a client
 * component cannot reach into the snapshot module to fetch them.
 *
 * One line of lead per block. Terms are never restated here: every rung word
 * comes from `progress.levels` in the published snapshot and is passed in.
 */

export const indexCopy = bilingual({
  en: {
    eyebrow: "Markets",
    title: "Markets",
    lead: "A kind of work a business sells. An AI update lands here, not on a job title.",
    statMarkets: "Markets",
    statMarketsNote: "{n} activities in them",
    statCovered: "With a reading",
    statCoveredNote: "{n} more that no update mentioned",
    statTop: "Furthest level reached",
    statTopTag: "{n} markets",
    statTopBlank: "No market has a reading yet",
    distTitle: "Where the evidence landed",
    distLead: "Pick a rung to see only the markets that reached it.",
    blankRung: "No reading",
    blankWord: "No collected update mentioned these markets",
    tableTitle: "All markets",
    tableLead: "A blank market means nothing was collected about it, not that AI does none of it.",
    tableLabel: "Markets table",
    searchLabel: "Search",
    searchPlaceholder: "English or Chinese name",
    coverageLabel: "Reading",
    coverageAll: "All",
    coverageWith: "With a reading",
    coverageWithout: "No reading",
    sortLabel: "Sort by",
    sortTop: "Furthest level",
    sortActivities: "Activities",
    sortScored: "With a reading",
    sortOccupations: "Occupations",
    showing: "Showing {n} of {total} markets",
    colMarket: "Market",
    colActivities: "Activities",
    colAssessed: "With a reading",
    colTop: "Furthest level reached",
    colOccupations: "Occupations served",
    noReading: "no update mentioned it",
    emptyTitle: "No market matches.",
    emptyWhy: "No market name contains what you typed, at the rung and coverage you picked.",
    reset: "Clear the filters",
    empty: "No market is published in this snapshot.",
  },
  "zh-CN": {
    eyebrow: "赛道",
    title: "赛道",
    lead: "企业卖给客户的一类工作。AI 更新落在这里，不落在职位上。",
    statMarkets: "赛道",
    statMarketsNote: "其中共 {n} 项活动",
    statCovered: "有读数",
    statCoveredNote: "另有 {n} 个赛道没被任何更新谈到",
    statTop: "已达到的最高层级",
    statTopTag: "{n} 个赛道",
    statTopBlank: "还没有赛道拿到读数",
    distTitle: "证据落在了哪里",
    distLead: "点一级，只看达到那一级的赛道。",
    blankRung: "无读数",
    blankWord: "采集到的更新里没有一条谈到这些赛道",
    tableTitle: "全部赛道",
    tableLead: "赛道是空的，只说明没采集到它，不说明 AI 做不了。",
    tableLabel: "赛道表",
    searchLabel: "搜索",
    searchPlaceholder: "中文名或英文名",
    coverageLabel: "读数",
    coverageAll: "全部",
    coverageWith: "有读数",
    coverageWithout: "没读数",
    sortLabel: "排序",
    sortTop: "最高层级",
    sortActivities: "活动数",
    sortScored: "有读数",
    sortOccupations: "服务职业数",
    showing: "显示 {total} 个赛道中的 {n} 个",
    colMarket: "赛道",
    colActivities: "活动数",
    colAssessed: "有读数",
    colTop: "已达到的最高层级",
    colOccupations: "服务的职业",
    noReading: "没有更新谈到它",
    emptyTitle: "没有赛道符合当前条件。",
    emptyWhy: "在你选的层级和读数条件下，没有赛道名包含你输入的字。",
    reset: "清除筛选",
    empty: "这份快照里没有发布任何赛道。",
  },
});

export const detailCopy = bilingual({
  en: {
    eyebrow: "Market",
    back: "All markets",
    metaSuffix: "Market",
    lead: "How far AI got on each activity in this market, and the update that showed it.",
    statActivities: "Activities",
    statActivitiesNote: "{n} with a reading",
    statTop: "Furthest level reached",
    statTopBlank: "No update mentioned this market",
    statReadings: "Readings",
    statReadingsNote: "{n} pulled back by an evidence tier",
    statGatedNote: "{n} held at L0 by a gate",
    activitiesTitle: "Activities in this market",
    activitiesLead: "Open a row to read the updates behind its level.",
    activitiesNone: "No activity is published for this market.",
    readingsLabel: "Readings table",
    colShows: "Published",
    colJudged: "Judged",
    colTierOne: "Evidence tier",
    colUpdate: "Update",
    colWhen: "When",
    readings: "readings",
    tasks: "tasks",
    noReadingsTitle: "No update in the collected window mentioned this activity.",
    noReadingsWhy: "That is a statement about the collection, not about the work.",
    capNote: "{tier} allows only L{cap}",
    gated: "Held by a gate",
    occupationsTitle: "Occupations this market is served by",
    occupationsLead: "One market is served by several occupations, so these are not shares of a job.",
    occupationsLabel: "Occupations table",
    occupationsNone: "No occupation has been linked to this market yet.",
    occupationsWhy: "The market-to-occupation edges are published per market; this one has none.",
    colOccupation: "Occupation",
    colConfidence: "Confidence",
    gatesTitle: "Gates holding activities here",
    gatesLead: "A gate holds an activity at L0 until the institution that wrote the rule changes it.",
    colGate: "Gate",
    colType: "Kind",
    colStatus: "Status",
    colHolds: "Activities held here",
    noReading: "no update mentioned it",
    source: "source",
  },
  "zh-CN": {
    eyebrow: "赛道",
    back: "全部赛道",
    metaSuffix: "赛道",
    lead: "这个赛道的每条活动到了第几级，凭哪条更新。",
    statActivities: "活动",
    statActivitiesNote: "其中 {n} 条有读数",
    statTop: "已达到的最高层级",
    statTopBlank: "没有更新谈到这个赛道",
    statReadings: "读数",
    statReadingsNote: "其中 {n} 条被证据层级压低",
    statGatedNote: "{n} 条被闸门按在 L0",
    activitiesTitle: "这个赛道里的活动",
    activitiesLead: "点开一条，就地读它凭的那几条更新。",
    activitiesNone: "这个赛道没有发布任何活动。",
    readingsLabel: "读数表",
    colShows: "发布值",
    colJudged: "判官值",
    colTierOne: "证据层级",
    colUpdate: "更新",
    colWhen: "时间",
    readings: "条读数",
    tasks: "项任务",
    noReadingsTitle: "采集窗口里没有一条更新谈到这条活动。",
    noReadingsWhy: "这是关于采集的陈述，不是关于这份工作的陈述。",
    capNote: "{tier} 最高只支持到 L{cap}",
    gated: "被闸门按住",
    occupationsTitle: "服务这个赛道的职业",
    occupationsLead: "一个赛道由多个职业共同服务，所以这些不是对某份工作的切分。",
    occupationsLabel: "职业表",
    occupationsNone: "还没有职业与这个赛道建立关联。",
    occupationsWhy: "赛道—职业的对应关系按赛道发布，这个赛道目前一条都没有。",
    colOccupation: "职业",
    colConfidence: "置信度",
    gatesTitle: "按住这个赛道的闸门",
    gatesLead: "闸门把活动按在 L0，直到写下这条规则的机构自己改口。",
    colGate: "闸门",
    colType: "类型",
    colStatus: "状态",
    colHolds: "在本赛道按住",
    noReading: "没有更新谈到它",
    source: "原文",
  },
});

/** `{n}` and friends, filled in without pulling a formatter into the bundle. */
export function fill(template: string, values: Record<string, string | number>): string {
  return Object.entries(values).reduce(
    (text, [key, value]) => text.replaceAll(`{${key}}`, String(value)),
    template,
  );
}

/** One grouping for both languages, so a number never changes shape mid-page. */
const numberFormat = new Intl.NumberFormat("en-US");

export function count(value: number): string {
  return numberFormat.format(value);
}
